#!/bin/bash
# Check for prerequisites
if [ "$(id -u)" -ne 0 ]; then
    echo "This script must be run using sudo!"
    exit 1
fi

# Copy top file
cp -av salt/top.sls /opt/so/saltstack/local/salt/top.sls

# Copy salt config
for i in elasticsearch firewall velociraptor /nginx/etc /common/tools/sbin; do
    mkdir -p $i
    cp -av salt/$i* /opt/so/saltstack/local/salt/$i;
done

# Copy pillar stuff
cp -av pillar/elasticsearch/* /opt/so/saltstack/local/pillar/elasticsearch

# Restart ES to load new config
so-elasticsearch-restart --force

# Common stuff
salt "*" saltutil.kill_all_jobs & salt-call state.apply common

# Apply new Velociraptor config
so-velociraptor-start --force

# Restart nginx
so-nginx-restart --force

